name: Deploy Fullstack Project to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            APP_DIR="/home/ubuntu/fullstack-project"

            echo "🚀 Starting deployment on EC2..."

            # Navigate to project directory or clone it
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/shivamshete92/fullstack-project.git "$APP_DIR"
            else
              cd "$APP_DIR"
              git reset --hard HEAD
              git pull origin main
            fi

            cd "$APP_DIR"

            # Build and deploy using Docker Compose
            docker compose down || true
            docker compose up -d --build

            echo "✅ Deployment complete!"
            echo " - Frontend: http://<EC2_PUBLIC_IP>:3000"
            echo " - Backend:  http://<EC2_PUBLIC_IP>:5000"

