name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/fullstack-app || git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git ~/fullstack-app
            cd ~/fullstack-app
            git reset --hard
            git pull origin main

            docker compose down
            docker compose up -d --build
